name: http_extensions_headers
description: An http extension that adds headers to requests.
version: 1.0.0
homepage: https://github.com/aloisdeniel/http_extensions

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.4.0
  http: ^0.13.3
  http_extensions: ^1.0.0
    #path: ../http_extensions
  logging: ^1.0.0