name: http_extensions_headers
description: An http extension that adds headers to requests.
version: 1.0.0
homepage: https://github.com/aloisdeniel/http_extensions
author: aloisdeniel <alois.deniel@outlook.com>

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.3.0
  http: ^0.13.0
  http_extensions: ^0.1.1
  logging: ^1.0.0

dependency_overrides:
 http_extensions: 
   path: ../http_extensions