name: http_extensions_cache
description: An http extension that caches requests.
version: 1.0.0
homepage: https://github.com/aloisdeniel/http_extensions
author: aloisdeniel <alois.deniel@outlook.com>

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.3.0
  http: ^0.13.0
  uuid: ^3.0.0-nullsafety.0
  http_extensions: ^1.0.0
  logging: ^1.0.0

dependency_overrides:
 http_extensions: 
   path: ../http_extensions